### ISSUE TITLE
timestamp accuracy in radiotap headers

### ISSUE THREAD

**Issue by 66Ronghua99** [radiotap/radiotap-library#12]
Hi, I have a question about the meaning of the "accuracy" field in the Radiotap header. It's not clearly explained on the webpage.
For instance, in the timestamp field, the unit is "usec" and the **"accuracy"** is "22", what's the meaning of such a value 22?
In addition, is there any way to set the accuracy as a nanosecond? E.g. modifying the driver?

**Comment by jmberg** [comment]
Sorry, I didn't get around to this ...

The definition of the accuracy is on the page:
https://www.radiotap.org/fields/timestamp.html

> precision
> 
> Defines the expected accuracy of the timestamp, in the same units as the timestamp.

So what your file says is that you have a timestamp in usec, and the accuracy is 22 usec.


You could only set the accuracy in the file to 1 usec if the unit is usec, but what would the point be, if the hardware doesn't record it with such precision?

To get nanosecond precision you'd probably have to build new hardware :-)
