### ISSUE TITLE
Parser is out of sync with spec.

### ISSUE THREAD

**Issue by Frostie314159** [radiotap/radiotap-library#15]
The Parser is lacking fields which were only recently added to the spec, like tlv and eht.

**Comment by jmberg** [comment]
Yes, but how's that an issue? It just means nobody needed it yet and implemented it.

**Comment by Frostie314159** [comment]
I mistook this parser for the reference implementation and misunderstood the standardisation process. I just thought, it could help understand these fields, since the spec can sometimes be a bit confusing and looking at the code can help.

**Comment by jmberg** [comment]
OK, fair enough. We don't really have a reference implementation, sadly. This diverged from wireshark a lot, so de facto, I guess wireshark is the reference, but it's not that great to reuse even if it was originally based on this code.

I think the part that this code covers wrt. parsing would be the easiest bit, understanding the actual contents of the fields tends to be much harder :)
