### ISSUE TITLE
How to calclulate the mcs index given IEEE80211_RADIOTAP_MCS

### ISSUE THREAD

**Issue by Consti10** [radiotap/radiotap-library#8]
Hello,
I cannot find any sources online on how to calculate the mcs_index given the `IEEE80211_RADIOTAP_MCS `param.
To clarify my issue:
If I want to calculate the bandwidth for example, radiotap.h neatly defines `IEEE80211_RADIOTAP_MCS_BW_MASK`
So I can just use `bandwidth= param & IEEE80211_RADIOTAP_MCS_BW_MASK;`
However, there is no such field for the mcs index.
Aka EEE80211_RADIOTAP_MCS_MCS_MASK
What would I have to use for `XXX` in this sense
`mcs_index= param & XXX;`

**Comment by jmberg** [comment]
http://www.radiotap.org/fields/MCS

documents that the field contains 3 bytes:
* known - the bits that are known
* flags - the flags field where also e.g. MCS_BW_MASK is
* mcs - the MCS number

So you don't need a bitmask for the third byte.

Note that this is only for HT, there are separate fields for VHT and HE.

**Comment by Consti10** [comment]
Does this mean I can safely use  `ieee80211_radiotap_iterator` in this manner:
```
switch (iterator.this_arg_index) 
...
case IEEE80211_RADIOTAP_MCS:
                    uint8_t known=iterator.this_arg[0];
                    uint8_t flags=iterator.this_arg[1];
                    uint8_t mcs=iterator.this_arg[2];

```

**Comment by jmberg** [comment]
Yes, this field is guaranteed to be 3 bytes.

**Comment by Consti10** [comment]
Thanks.
I was assuming that iterator.this_arg always gives you one byte per argument index, because most example code does so.
However,looking back at it now I know that these examples only used arguments which are 1 byte big, like the "Antenna" argument.
If anyone comes across this issue, here is the code how I do the parsing right now:
https://github.com/Consti10/wifibroadcast/blob/78ee09eac944a358b7409a2806cf7166d168b031/src/RadiotapHeader.hpp#L243
