### ISSUE TITLE
I get the channel flags when expecting the channel frequency

### ISSUE THREAD

**Issue by linxcow** [radiotap/radiotap-library#9]
Am i doing something wrong ? : see below

         case IEEE80211_RADIOTAP_CHANNEL:
           printf("\tchannel frequency: %d\n", (u_int16_t)*iter->this_arg);
           break;

I am getting :  
        
        channel frequency: 128

**Comment by jmberg** [comment]
You're doing it wrong, you need `*(uint16_t *)iter->this_arg`

**Comment by linxcow** [comment]
And to get the flags can I use  this ? : `   *(uint16_t *)iter->(this_arg+2)  `
